---
#core dont just v1
apiVersion: v1
kind: Namespace
metadata: 
    name: myns
    labels: 
        dept: engineering
---
# write the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fortune-deploy
    namespace: myns
    labels:
        dept: engineering
        app: fortune
spec:
    replicas: 2
    selector:
        matchLabels:
            app: fortune-pod
    template:
        #pod yaml file
        metadata: 
            name: fortune-pod
            labels:
                dept: engineering
                app: fortune-pod
        spec:
            containers:
            - name: fortune-container
              image: ybng/fortune:v2
              imagePullPolicy: IfNotPresent
              ports:
              - name: http-port
                containerPort: 3000

